import { Employee } from '@/modules/maas-kesinti/types/employee';

interface IndividualPaySlipData { employee: Employee; month: string; paymentDate: string; }

export function printIndividualPaySlip(data: IndividualPaySlipData) {
  const { employee, month, paymentDate } = data;
  const totalAdvances = employee.advances.reduce((sum, adv) => sum + adv.amount, 0);
  const formatCurrency = (amount: number) => new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY' }).format(amount);
  const today = new Date();
  const formattedDate = today.toLocaleDateString('tr-TR', { day: '2-digit', month: '2-digit', year: 'numeric' });
  const docNumber = `${today.getFullYear()}/${String(Date.now()).slice(-4)}`;
  const printWindow = window.open('', '_blank');
  if (!printWindow) { alert('Lütfen popup engelleyiciyi kapatın'); return; }
  printWindow.document.write(`<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Maaş Belgesi - ${employee.name}</title><style>@page{size:A4;margin:20mm 25mm}*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Times New Roman',serif;font-size:13px;line-height:1.7;color:#1a1a1a;padding:10px}.page{background:white;max-width:210mm;min-height:297mm;margin:0 auto;padding:30mm 25mm;box-shadow:0 2px 20px rgba(0,0,0,0.1)}.header{text-align:center;border-bottom:2px solid #1a1a1a;padding-bottom:15px;margin-bottom:30px}.meta-row{display:flex;justify-content:space-between;margin-bottom:6px}.subject{text-align:center;font-weight:bold;font-size:14px;margin-bottom:25px;text-decoration:underline}.info-table{width:100%;border-collapse:collapse;margin-bottom:25px}.info-table td{padding:8px 12px;border:1px solid #ccc;font-size:13px}.info-table td:first-child{width:45%;font-weight:bold;background:#f9f9f9}.editable-field{border:none;border-bottom:1px solid #999;outline:none;font-family:inherit;font-size:13px;padding:2px 4px;min-width:200px}.signature-area{margin-top:50px}.signature-line{border-top:1px solid #333;width:200px;padding-top:6px;font-size:12px;font-weight:bold}@media print{body{padding:0}.page{box-shadow:none;padding:0;min-height:auto;max-width:100%}}</style></head><body><div class="page"><div class="header"><h2>ZORLU DIGITAL PLAZA</h2></div><div class="meta-row"><span><strong>Tarih:</strong> ${formattedDate}</span><span><strong>Sayı:</strong> ${docNumber}</span></div><div class="subject">Konu: Maaş ve Çalışma Bilgisi Teyidi</div><div>İlgili Banka Yetkilisine,</div><p style="margin:20px 0">Şirketimiz bünyesinde çalışan maaş ve istihdam bilgileri aşağıdaki gibidir:</p><table class="info-table"><tr><td>Adı Soyadı</td><td>${employee.name}</td></tr><tr><td>Kimlik No / Pasaport No</td><td><input type="text" class="editable-field" placeholder="Giriniz..." /></td></tr><tr><td>Pozisyon / Ünvan</td><td><input type="text" class="editable-field" placeholder="Giriniz..." /></td></tr><tr><td>Brüt Aylık Maaş</td><td>${formatCurrency(employee.salary)}</td></tr><tr><td>Ödeme Günü</td><td>Her ayın 1'i</td></tr><tr><td>Ödeme Şekli</td><td>Banka Havalesi</td></tr></table><p>Bu yazı talep üzerine düzenlenmiş olup, şirket kayıtlarımız esas alınarak hazırlanmıştır.</p><div class="signature-area"><div style="margin-bottom:50px;font-weight:bold">Saygılarımızla,</div><div class="signature-line">İmza / Kaşe<div style="font-size:11px;color:#555">Zorlu Digital Plaza</div></div></div></div><script>window.onload=function(){setTimeout(function(){window.print()},500)}</script></body></html>`);
  printWindow.document.close();
}
