import { Employee } from '@/modules/maas-kesinti/types/employee';

interface PaySlipData { employee: Employee; netPayment: number; totalAdvances: number; month: string; paymentDate: string; }

export function printPaySlips(paySlips: PaySlipData[]) {
  const formatCurrency = (amount: number) => new Intl.NumberFormat('tr-TR', { style: 'currency', currency: 'TRY' }).format(amount);
  const printWindow = window.open('', '_blank');
  if (!printWindow) { alert('Lütfen popup engelleyiciyi kapatın'); return; }
  printWindow.document.write(`<!DOCTYPE html><html lang="tr"><head><meta charset="UTF-8"><title>Maaş Bordroları</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Segoe UI',sans-serif;background:#f5f5f5;padding:20px}.pay-slip{background:white;border:2px solid #B91C1C;border-radius:8px;padding:30px;margin-bottom:30px;page-break-after:always;max-width:600px;margin-left:auto;margin-right:auto}.pay-slip:last-child{page-break-after:avoid}.header{text-align:center;border-bottom:2px solid #B91C1C;padding-bottom:20px;margin-bottom:20px}.company-name{font-size:28px;font-weight:bold;color:#B91C1C}.title{font-size:18px;font-weight:bold;margin-top:15px}.employee-info{margin-bottom:20px;padding:15px;background:#f9f9f9;border-radius:6px}.employee-name{font-size:20px;font-weight:bold}.detail-row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #eee}.detail-value.negative{color:#DC2626}.total-row{display:flex;justify-content:space-between;padding:20px;background:#B91C1C;color:white;border-radius:6px;margin-top:20px}.total-value{font-size:24px;font-weight:bold}.footer{margin-top:30px;padding-top:20px;border-top:1px solid #eee;display:flex;justify-content:space-between}.signature-box{text-align:center;width:45%}.signature-line{border-top:1px solid #333;margin-top:50px;padding-top:10px;font-size:12px;color:#666}@media print{body{background:white;padding:0}}</style></head><body>${paySlips.map(slip => `<div class="pay-slip"><div class="header"><div class="company-name">ZORLU DIGITAL PLAZA</div><div class="title">MAAŞ BORDROSU</div></div><div class="employee-info"><div class="employee-name">${slip.employee.name}</div><div style="color:#666">${slip.employee.country}</div></div><div><div class="detail-row"><span>Dönem</span><span>${slip.month}</span></div><div class="detail-row"><span>Brüt Maaş</span><span>${formatCurrency(slip.employee.salary)}</span></div><div class="detail-row"><span>Toplam Avans Kesintisi</span><span class="detail-value negative">-${formatCurrency(slip.totalAdvances)}</span></div></div><div class="total-row"><span>NET ÖDENEN</span><span class="total-value">${formatCurrency(slip.netPayment)}</span></div><div class="footer"><div class="signature-box"><div class="signature-line">İşveren İmza</div></div><div class="signature-box"><div class="signature-line">Çalışan İmza</div></div></div></div>`).join('')}<script>window.onload=function(){window.print()}</script></body></html>`);
  printWindow.document.close();
}
